[package]
name = "mini_md"
version = "0.1.0"
authors = ["tmendonca28 <tmendonca28@gmail.com>"]
edition = "2018"
description = "A simple markdown compiler to learn Rust"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
